language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
before_install: 
  - set -ev
  - sudo apt-get install binutils 
  - sudo apt-get install libproj-dev 
  - sudo apt-get install gdal-bin
  - sudo apt-get install libgeoip1       #for GeoIP support
  - sudo apt-get install python-gdal     #for GDAL’s own Python bindings – includes interfaces for raster manipulation  
  - sudo apt-get install spatialite-bin  
  - cd geodjangoSpatialite
install: 
  - pip install Django==$DJANGO_VERSION
script: python manage.py test testsite
